In [1]:
import pandas as pd

import numpy as np

import os

In [2]:
os.listdir()

['.ipynb_checkpoints',
 '2024 RFQ(1)_Eric Habarth - Copy.xlsx',
 '2024 RFQ[1]_Eric Habarth - Copy.xlsx',
 'Alt Rate - ARCBest CSP.xls',
 'Alt Rate EXLA CSP.xls',
 'Alt Rate ImprimusBrea DYLT.xls',
 'Alt Rate Template - ARCRATE CSP.xls',
 'Alt Rates',
 'Alt Rate_DYLT_imprimus v3.xls',
 'Appendix B Discount and MC Matrix.xlsx',
 'Blank Alt Rate Template.xls',
 'Canada zips.csv',
 'Can_Test.xlsx',
 'Carrier - US 2023 Ship Data CCOII_Bradley Klein.xlsx',
 'Chunk Folder',
 'chunkedfile.xlsx',
 'chunked_file.xlsx',
 'cleaned_zips.csv',
 'Cleaning ugly zip code file.ipynb',
 'CME Freight shipments 2024_James Lohmer.xlsx',
 'combining chunked spreadsheets.ipynb',
 'comb_fl',
 'Copy of Can_Test.xls',
 'Copy of Nolan CFS to MIA (1)_Joshua Trickel (1).xlsx',
 'CrdFnding_Shipping Est (1)_Justin VanOver (1).xlsx',
 'desktop.ini',
 'df.explode().ipynb',
 'Dialpad.lnk',
 'Edge',
 'Edge output files',
 'Edge split',
 'edge template.xls',
 'edge template_Klein.xls',
 'expirement.csv',
 'expl_practice.csv',
 'FAK generator',
 'farmer results.xlsx',
 'farmerbrosorig.xlsx',
 'Farmplast- Pricing - WARD.xlsx',
 'FCSY CSP Alt Rate.xls',
 'FedEx USA Inbound Analysis (1).xlsx',
 'Firefox.lnk',
 'FP-FRZF v3.xls',
 'gls_fuel.xls',
 'gls_fuel.xlsx',
 'gls_rules_tariff.xlsx',
 'Kutools for Excel.lnk',
 'linehaul',
 'Linehual Script.ipynb',
 'lohmer.xlsx',
 'Margin_vs_Markup-1.pdf',
 'MercuryEdge (t-insight).lnk',
 'merged_zips.csv',
 'merge_all.csv',
 'Merge_Report_2024_kelly_clawson_1800w.xls',
 'merge_st.csv',
 'merge_standard.csv',
 'Pandas merging',
 'Pandas_source_files',
 'rate build Vinent Practice.xls',
 'rate build_sunny_sky.xls',
 'Rating_Report_Hamricks.xls',
 'Rating_Report_james.xls',
 'Rating_Report_james_lohmer.xls',
 'Rating_Report_no_systems.xls',
 'Rating_Report_titan3_ABF.xls',
 'Rating_Report_titan3_ctii.xls',
 'Remove State names and add city zips .ipynb',
 'report1710336887753.xls',
 'report1710336887753.xlsx',
 'sample clean.xlsx',
 'Screenshot 2024-03-26 141008.png',
 'Slack.lnk',
 'Source Files',
 'statenames.xlsx',
 'Temp - Shortcut.lnk',
 'Template files',
 'training docs',
 'Untitled.ipynb',
 'val_sol_edge_all.xls',
 'val_sol_edge_st.xls',
 'Vlookups',
 'WT03152024_Kekoa Carville.xlsx',
 'Zip Cleaning',
 'Zip cleaning.ipynb',
 'Zip Code list (NTG LTL Quote)_Kelly Dawson.xlsx',
 'ZIP_Locale_Detail.xls',
 '_Restructuring fuel tables.ipynb']

In [3]:
df = pd.read_excel('Farmplast- Pricing - WARD.xlsx')

In [29]:
res = df.Destination.str.len().sort_values().index

In [31]:
df = df.reindex(res).head(60)

,SCAC,Account Name,Origin,Destination,Direct/ Interline,Discount,Minimum Charge
0,WARD,Farmplast,7054,NJ,Direct,0.905,115.00
38,WARD,Farmplast,7054,KY,Direct,0.895,130.00
37,WARD,Farmplast,7054,SC,Direct,0.901,130.00
52,WARD,Farmplast,7054,IL,Direct,0.879,135.00
53,WARD,Farmplast,7054,WI,Direct,0.879,135.00
54,WARD,Farmplast,7054,ON,Direct,0.770,179.25
14,WARD,Farmplast,7054,PA,Direct,0.923,115.00
55,WARD,Farmplast,7054,QC,Direct,0.770,222.75
47,WARD,Farmplast,7054,458,Direct,0.906,130.00
31,WARD,Farmplast,7054,270,Direct,0.800,182.00
48,WARD,Farmplast,7054,480,Direct,0.800,182.00
29,WARD,Farmplast,7054,260,Direct,0.885,130.00
27,WARD,Farmplast,7054,254,Direct,0.885,130.00
21,WARD,Farmplast,7054,219,Direct,0.914,130.00
19,WARD,Farmplast,7054,217,Direct,0.914,130.00
18,WARD,Farmplast,7054,216,Direct,0.900,130.00
20,WARD,Farmplast,7054,218,Direct,0.900,130.00
40,WARD,Farmplast,7054,433,Direct,0.886,130.00
13,WARD,Farmplast,7054,149,Direct,0.905,130.00
12,WARD,Farmplast,7054,148,Direct,0.800,182.00
9,WARD,Farmplast,7054,139,Direct,0.905,130.00
8,WARD,Farmplast,7054,138,Direct,0.800,182.00
7,WARD,Farmplast,7054,137,Direct,0.905,130.00
70,WARD,Farmplast,PA,7054,Direct,0.923,115.00
71,WARD,Farmplast,197-198,7054,Direct,0.900,130.00
86,WARD,Farmplast,261-268,7054,Direct,0.800,182.00
85,WARD,Farmplast,260,7054,Direct,0.885,130.00
84,WARD,Farmplast,255-259,7054,Direct,0.800,182.00
83,WARD,Farmplast,254,7054,Direct,0.885,130.00
72,WARD,Farmplast,199-205,7054,Direct,0.900,130.00
73,WARD,Farmplast,206-215,7054,Direct,0.914,130.00
78,WARD,Farmplast,220-229,7054,Direct,0.893,130.00
75,WARD,Farmplast,217,7054,Direct,0.914,130.00
79,WARD,Farmplast,230-232,7054,Direct,0.907,130.00
81,WARD,Farmplast,241-246,7054,Direct,0.800,182.00
80,WARD,Farmplast,233-240,7054,Direct,0.893,130.00
76,WARD,Farmplast,218,7054,Direct,0.900,130.00
77,WARD,Farmplast,219,7054,Direct,0.914,130.00
87,WARD,Farmplast,270,7054,Direct,0.800,182.00
74,WARD,Farmplast,216,7054,Direct,0.900,130.00
82,WARD,Farmplast,247-253,7054,Direct,0.800,182.00
93,WARD,Farmplast,SC,7054,Direct,0.901,130.00
89,WARD,Farmplast,275-277,7054,Direct,0.874,130.00
113,WARD,Farmplast,010-069,7054,Interline,0.890,180.00
111,WARD,Farmplast,QC,7054,Direct,0.770,222.75
110,WARD,Farmplast,ON,7054,Direct,0.770,179.25
109,WARD,Farmplast,WI,7054,Direct,0.879,135.00
108,WARD,Farmplast,IL,7054,Direct,0.879,135.00
107,WARD,Farmplast,492-495,7054,Direct,0.800,182.00
106,WARD,Farmplast,483-490,7054,Direct,0.800,182.00
105,WARD,Farmplast,481-482,7054,Direct,0.887,130.00
104,WARD,Farmplast,480,7054,Direct,0.800,182.00
103,WARD,Farmplast,458,7054,Direct,0.906,130.00
102,WARD,Farmplast,453-457,7054,Direct,0.886,130.00
101,WARD,Farmplast,450-452,7054,Direct,0.886,130.00
100,WARD,Farmplast,444-449,7054,Direct,0.886,130.00
99,WARD,Farmplast,440-443,7054,Direct,0.906,130.00
98,WARD,Farmplast,437-439,7054,Direct,0.886,130.00
97,WARD,Farmplast,434-436,7054,Direct,0.906,130.00
96,WARD,Farmplast,433,7054,Direct,0.886,130.00

In [32]:
df.to_excel('reindexed_farm_ward.xlsx')

In [5]:
df['Destination'] =df['Destination'].apply(str)

In [20]:
df.sort_values(by='Destination', key=str.contains'-')

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1602584159.py, line 1)

In [6]:
df['Destination'] = df['Destination'].fillna(0)

In [7]:
df['Destination'].value_counts(dropna=False)

Destination
7054                     57
Ward direct points        8
483-490                   1
480                       1
458                       1
                         ..
255-259                   1
260                       1
261-268                   1
270                       1
Ward Interline points     1
Name: count, Length: 68, dtype: int64

In [8]:
df

,SCAC,Account Name,Origin,Destination,Direct/ Interline,Discount,Minimum Charge
0,WARD,Farmplast,7054,NJ,Direct,0.905,115.00
1,WARD,Farmplast,7054,100-104,Direct,0.800,259.25
2,WARD,Farmplast,7054,105-109,Direct,0.905,130.00
3,WARD,Farmplast,7054,110-119,Direct,0.800,259.25
4,WARD,Farmplast,7054,120-124,Direct,0.800,182.00
...,...,...,...,...,...,...,...
126,WARD,Farmplast,Ward direct points,"DE/DC/MD/VA (199-205, 216, 218)",Direct 3rd party,0.750,200.00
127,WARD,Farmplast,"DE/DC/MD/VA (199-205, 216, 218)",Ward direct points,Direct 3rd party,0.750,200.00
128,WARD,Farmplast,All other Ward direct points,All other Ward direct points,Direct 3rd party,0.800,150.00
129,WARD,Farmplast,Ward direct points,Ward Interline points,Interline 3rd party,0.750,295.00
130,WARD,Farmplast,Ward Interline points,Ward direct points,Interline 3rd party,0.650,450.00

In [9]:
df['Destination'] = df['Destination'].str.replace('-','0')

In [10]:
#df['Destination'] = df['Destination'].str.replace(',','0')

In [11]:
no_st = df[df['Destination'].str.isdigit()]

In [12]:
no_st.Destination.value_counts()

Destination
7054       57
1000104     1
4340436     1
260         1
2610268     1
270         1
2710274     1
2750277     1
2780279     1
2800282     1
4300432     1
433         1
4370439     1
254         1
4400443     1
4440449     1
4500452     1
4530457     1
458         1
480         1
4810482     1
4830490     1
4920495     1
2550259     1
2470253     1
1050109     1
2410246     1
1100119     1
1200124     1
1250127     1
1280136     1
137         1
138         1
139         1
1400143     1
1440147     1
148         1
149         1
1970198     1
1990205     1
2060215     1
216         1
217         1
218         1
219         1
2200229     1
2300232     1
2330240     1
0100069     1
Name: count, dtype: int64

In [13]:

st = df[~df['Destination'].str.isdigit()]

In [14]:
st

,SCAC,Account Name,Origin,Destination,Direct/ Interline,Discount,Minimum Charge
0,WARD,Farmplast,7054,NJ,Direct,0.905,115.00
14,WARD,Farmplast,7054,PA,Direct,0.923,115.00
36,WARD,Farmplast,7054,"283, 285, 286",Direct,0.800,182.00
37,WARD,Farmplast,7054,SC,Direct,0.901,130.00
38,WARD,Farmplast,7054,KY,Direct,0.895,130.00
52,WARD,Farmplast,7054,IL,Direct,0.879,135.00
53,WARD,Farmplast,7054,WI,Direct,0.879,135.00
54,WARD,Farmplast,7054,ON,Direct,0.770,179.25
55,WARD,Farmplast,7054,QC,Direct,0.770,222.75
114,WARD,Farmplast,Ward direct points,"NY (1000104, 1100119)",Direct 3rd party,0.750,260.00
115,WARD,Farmplast,"NY (100-104, 110-119)",Ward direct points,Direct 3rd party,0.750,260.00
116,WARD,Farmplast,Ward direct points,"NY (1200124, 1280136, 138, 148)",Direct 3rd party,0.750,200.00
117,WARD,Farmplast,"NY (120-124, 128-136, 138, 148)",Ward direct points,Direct 3rd party,0.750,200.00
118,WARD,Farmplast,Ward direct points,"NC (270, 2780279, 283, 285, 286)",Direct 3rd party,0.750,200.00
119,WARD,Farmplast,"NC (270, 278-279, 283, 285, 286)",Ward direct points,Direct 3rd party,0.750,200.00
120,WARD,Farmplast,Ward direct points,VA (2410246),Direct 3rd party,0.750,200.00
121,WARD,Farmplast,VA (241-246),Ward direct points,Direct 3rd party,0.750,200.00
122,WARD,Farmplast,Ward direct points,"WV (2470253, 2550259, 2610268)",Direct 3rd party,0.750,200.00
123,WARD,Farmplast,"WV (247-253, 255-259, 261-268)",Ward direct points,Direct 3rd party,0.750,200.00
124,WARD,Farmplast,Ward direct points,"MI (480, 4830490, 4920495",Direct 3rd party,0.750,200.00
125,WARD,Farmplast,"MI (480, 483-490, 492-495",Ward direct points,Direct 3rd party,0.750,200.00
126,WARD,Farmplast,Ward direct points,"DE/DC/MD/VA (1990205, 216, 218)",Direct 3rd party,0.750,200.00
127,WARD,Farmplast,"DE/DC/MD/VA (199-205, 216, 218)",Ward direct points,Direct 3rd party,0.750,200.00
128,WARD,Farmplast,All other Ward direct points,All other Ward direct points,Direct 3rd party,0.800,150.00
129,WARD,Farmplast,Ward direct points,Ward Interline points,Interline 3rd party,0.750,295.00
130,WARD,Farmplast,Ward Interline points,Ward direct points,Interline 3rd party,0.650,450.00

In [17]:
comb = pd.concat([no_st,st])

exp= comb.to_excel('farm_ward.xlsx')

In [15]:
df['Least'] = df['Least'].str.replace("$","")
df['Least'] = df['Least'].str.replace("%","")

KeyError: 'Least'

In [ ]:
df['Least'] = df['Least'].astype(float)

In [ ]:
first = [1,2,3,4,5]

In [ ]:
second =

In [ ]:
second

In [ ]:
df.columns

In [ ]:
df1 = df.iloc[0::6]

In [ ]:
df2 = df.iloc[1::6]

In [ ]:
df3 = df.iloc[3::6]

In [ ]:
df4 = df.iloc[4::6]

In [ ]:
df4

In [ ]:
df3['Least'] = df3['Least'].astype(int)

In [ ]:
df3['Most'] = df3['Least']+.049

In [ ]:
df3

In [ ]:
df2.Least

In [ ]:
df1['Per'] = df2['Least'].values

In [ ]:
df1['Least2'] = df3.Least.values

In [ ]:
df1['Most'] = df1['Least']+.049

In [ ]:
df1

In [ ]:
df1['Per2'] = df4.Least.values

In [ ]:
df1['Most2'] = df1['Least2']+.049

In [ ]:
df1.to_excel('gls_fuel.xlsx')