In [1]:
import pandas as pd
import numpy as np
import glob
import os
import xlwings as xw

In [2]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\Downloads\*xlsx') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\Downloads\Q3shipmentdata.xlsx

In [3]:
excel_file = pd.ExcelFile(latest_file)
sheet_names = excel_file.sheet_names

print(sheet_names)

['Sheet1']

In [33]:
print(latest_file)

C:\Users\matthew.shuff\Downloads\Q3shipmentdata.xlsx

In [4]:
df = pd.read_excel(latest_file)

In [5]:
df

,Ship Date,Account Name,BOL#,Origin Zip Code,Origin City,Origin State,Destination Zip Code,Destination City,Destination State,Length,Width,Height,Pallet Count,Total Weight,Freight Class,Accessorials,Total Freight Cost
0,2025-09-25,"WALDEEP, INC.",FPX00331990,92337,Fontana,CA,92708,Fountain Valley,CA,63,26,46,1,262,175.0,Delivery Appointment,76.98
1,2025-08-26,"WALDEEP, INC.",FPX00323000,91730,Rancho Cucamonga,CA,93012,Camarillo,CA,22,22,81,1,225,100.0,Liftgate at Delivery; Delivery Appointment,100.93
2,2025-09-05,"WALDEEP, INC.",FPX00326362,91761,Ontario,CA,91303,Canoga Park,CA,24,19,57,1,373,65.0,Liftgate at Delivery; Delivery Appointment,107.38
3,2025-07-30,"WALDEEP, INC.",FPX00315422,92337,Fontana,CA,91401,Valley Glen,CA,44,36,55,1,342,125.0,Liftgate at Delivery; Delivery Appointment,107.59
4,2025-09-12,"WALDEEP, INC.",FPX00328414,91761,Ontario,CA,91767,Pomona,CA,47,27,20,1,395,65.0,Liftgate at Delivery; Delivery Appointment,107.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,2025-09-29,"WALDEEP, INC.",FPX00332789,92337,Fontana,CA,66411,Blue Rapids,KS,29,26,41,1,552,60.0,Liftgate at Delivery; Residential Delivery; De...,407.34
485,2025-09-02,"WALDEEP, INC.",FPX00325095,91761,Ontario,CA,8054,Mt Laurel Township,NJ,51,53,56,1,419,175.0,Liftgate at Delivery; Delivery Appointment,412.74
486,2025-08-18,"WALDEEP, INC.",FPX00320854,92337,Fontana,CA,49098,Watervliet,MI,56,40,74,1,699,125.0,Liftgate at Delivery; Residential Delivery; De...,433.60
487,2025-08-25,"WALDEEP, INC.",FPX00322990,30093,Norcross,GA,30043,Lawrenceville,GA,37,17,29,1,197,70.0,Liftgate at Delivery; Residential Delivery; De...,487.43
488,2025-08-29,"WALDEEP, INC.",FPX00324254,92337,Fontana,CA,58801,Williston,ND,48,48,68,1,1361,70.0,Liftgate at Delivery; Residential Delivery; De...,652.22

In [6]:
columns = df.columns.str.upper()

In [15]:
df2 = pd.read_excel(latest_edge)

In [ ]:
df.columns

In [16]:
df = df[['BOL#','Account Name']]

In [31]:
df2['Primary Reference'] =df2['Primary Reference'].apply(str)

In [32]:
df.merge(df2, left_on='BOL#',right_on='Primary Reference',how='inner')

Empty DataFrame
Columns: [BOL#, Account Name, OID, Primary Reference, Type, Lane ID, Carrier Name, Carrier SCAC, Contract Name, Contract Mode, Contract Service, Service Days, Service Days Type, Minimum, Manual, Allocated, GL Code, Sequence, Total, Normalized Total, Item Total, Adjustment Total, Deficit Total, Discount Total, Fuel Total, Accessorial Total, Pct Accessorial Total, Accessorial Summary]
Index: []

[0 rows x 28 columns]

In [ ]:
col_list = df.columns

In [ ]:
col_list = col_list[0]

In [ ]:
col_list

In [ ]:
df.merge(latest_edge,left_on=df[col_list],right_on="Primary Reference", how='inner')

df_filt= df.loc[:, df.columns.str.contains('Primary Reference|PR|BOL|ID|zip|class|Class|weight|Weight|Pallet|Qty|acc|Length|Width|Height|L|W|H|Dimensions|Dims')]

# Review filtered df before exporting to make sure col names are in order

In [ ]:
df_filt = df_filt[['PR','Weight','Actual Class','Origin Zip','Destination Zip', 'Qty']]

In [ ]:
df_filt.to_excel('Template Files/Auto_file.xlsx', index=False)

In [10]:
latest_edge = glob.glob(r'C:\Users\matthew.shuff\AppData\Local\Temp\*.xls')

latest_edge = max(latest_edge, key=os.path.getmtime)
print(latest_edge)

C:\Users\matthew.shuff\AppData\Local\Temp\Rating_Report_2025_11_06_13_49_55.xls

In [ ]:
latest_template = glob.glob(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Edge\*.xls')

latest_template = max(latest_template, key=os.path.getmtime)
print(latest_template)

In [ ]:
latest_edge

In [ ]:
latest_file

In [ ]:
import xlwings as xw
    
app = xw.App()
wb = app.books.open(latest_edge)

In [ ]:
wb

In [ ]:
wb2 = app.books.open(latest_template)

In [ ]:
wb2.sheets[0].range('B' + str(wb2.sheets[0].cells.last_cell.row)).end('up').row

In [ ]:
Norm_tl_select = wb.sheets[0].range('R1:'+"R"+R_end)

In [ ]:
Scac_select = wb.sheets[0].range('F1:'+"F"+R_end)

In [ ]:
Norm_tl_select.copy()

In [ ]:
Scac_select.copy()

In [ ]:
last_col = wb2.sheets[0].range((1,1)).expand("right").column

last_col

In [ ]:
last_col = last_col+1

In [ ]:
scac_col = last_col+1

In [ ]:
wb2.sheets[0].range((1,last_col)).paste()

In [ ]:
Scac_select.copy()

In [ ]:
wb2.sheets[0].range((1,scac_col)).paste()

In [ ]:
end= wb2.sheets[0].range('A1').end('down').row

In [ ]:
last_col = wb2.sheets[0].range((end,last_col)).expand("down")
last_col

In [ ]:
last_col.copy()

In [ ]:
last_col.paste()

wb2.sheets[0].range("J2").paste(paste='values')

In [ ]:
norm_tl = wb.sheets[0].range('R1').end('down').row

In [ ]:
norm_tl.copy()

In [ ]:
first_sheet_end

In [ ]:
copyTI = wb.sheets[0].range('A2:'+ 'Z' + first_sheet_end).value

copywgt = wb.sheets[0].range('B2:'+ 'B' + first_sheet_end)

copycl = wb.sheets[0].range('C2:'+ 'C' + first_sheet_end)

copyor = wb.sheets[0].range('I2:'+ 'I' + first_sheet_end)

copydest = wb.sheets[0].range('J2:'+ 'J' + first_sheet_end)

copyplt = wb.sheets[0].range('F2:'+ 'F' + first_sheet_end)

In [ ]:
copyTI

In [ ]:
copyTI.copy()

target_sheet = wb2.sheets[0].range("A2")

In [ ]:
import xlwings as xw
import win32com.client as win32 # For accessing Excel constants

copyTI.copy() # Copy the range

        # Paste values using PasteSpecial
target_sheet.api.PasteSpecial(Paste=win32.constants.xlPasteValues)

In [ ]:
copywgt.copy()

wb2.sheets[0].range("B2").paste(paste='values')

In [ ]:
copycl.copy()

wb2.sheets[0].range("C2").paste(paste='values')

In [ ]:
copyor.copy()

wb2.sheets[0].range("I2").paste(paste='values')

In [ ]:
copydest.copy()

wb2.sheets[0].range("J2").paste(paste='values')

In [ ]:
copyplt.copy()

wb2.sheets[0].range("P2").paste(paste='values')

In [1]:
csts[1]

NameError: name 'csts' is not defined

In [ ]:
wb.save()