In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas Custom 2')

['Ahmos.xlsx',
 'Bollards Plus LTL Pricing Workbook April 2024 (1) (1).xlsx',
 'edge template-RyanViz8.27dims.xls',
 'Fedex Fuel discrepancies.xlsx',
 'Halpern - Rerate - Edge Format - Item Level with Costs.xlsx',
 'Halpernlineup.xlsx',
 'Khalil hope to god done.xlsx',
 'Khalil Merged w dims.xlsx',
 'Khalil Merged w dims2.xlsx',
 'Khalil8.14.xlsx',
 'LHalpern.xlsx',
 'Output from Alteryx (1).xlsx',
 'Proposal_Formwoood Industires_RDFS_9.16.24.xlsb',
 'Q2 24 RTC Freight_Ahmos III Zu-Bolton.xlsx',
 'R+l Tariff.xlsx',
 'Rating_Report_Halpern.xls',
 'Rating_Report_twisters.xls',
 'RDFS FW Fuel Surcharge.xls',
 'RV8.27.xlsx',
 'rvblankdims.xlsx',
 'rv_nondupedims.xlsx',
 'Shipping 08_14_2024_Ryan Vissotzky.xlsx',
 'sortedhalpern.xlsx',
 'twisters.xlsx',
 'WM Twisters Promo 9-11-24 (2).xlsx',
 'WM Twisters Promo 9-11-24.xlsx']

In [3]:
df = pd.read_excel('Pandas Custom 2\RDFS FW Fuel Surcharge.xls', sheet_name='Sheet2')

df1 = pd.read_excel('Pandas Custom 2\Rating_Report_twisters.xls')

In [4]:
df

         FSC
0       1.50
1       1.55
2     18.55%
3     37.10%
4       1.55
..       ...
355  101.70%
356     5.95
357     6.00
358   51.25%
359  102.50%

[360 rows x 1 columns]

In [5]:
first_fuel_col = df.iloc[::4, :]

In [26]:
Second_fl_col = df[1::4]

In [27]:
Second_fl_col

      FSC
1    1.55
5    1.60
9    1.65
13   1.70
17   1.75
..    ...
341  5.80
345  5.85
349  5.90
353  5.95
357  6.00

[90 rows x 1 columns]

In [7]:
surcharge = Second_fl_col = df[2::4]

In [8]:
first_fuel_col = first_fuel_col.reset_index()

In [9]:
first_fuel_col.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89]

In [28]:
Second_fl_col = Second_fl_col.reset_index()

In [29]:
Second_fl_col

    index   FSC
0       1  1.55
1       5  1.60
2       9  1.65
3      13  1.70
4      17  1.75
..    ...   ...
85    341  5.80
86    345  5.85
87    349  5.90
88    353  5.95
89    357  6.00

[90 rows x 2 columns]

In [13]:
surcharge = surcharge['FSC']

In [14]:
surcharge = surcharge.reset_index()

In [25]:
surcharge

    index     FSC
0       2  18.55%
1       6  18.85%
2      10  19.15%
3      14  19.45%
4      18  19.75%
..    ...     ...
85    342  49.65%
86    346  50.05%
87    350  50.45%
88    354  50.85%
89    358  51.25%

[90 rows x 2 columns]

In [15]:
first_fuel_col =first_fuel_col['FSC']

In [20]:
df['FL_1'] = first_fuel_col.values

ValueError: Length of values (90) does not match length of index (360)

In [21]:
d = {'FL_1' : first_fuel_col,}

df2 = pd.DataFrame(data=d, index=Second_fl_col.index)

In [30]:
df2['FL_2'] = Second_fl_col['FSC'].values

In [32]:
df2['SRC'] = surcharge['FSC'].values

In [34]:
df2.to_excel('Alt Rates/RDFS fw fuelsrc.xlsx')