In [1]:
import pandas as pd

import numpy as np

import os

from ast import literal_eval

import glob

In [3]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\Downloads\*.xlsx') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\Downloads\TrueCare % Nolan Transportation Proposal (1) (2).xlsx

In [6]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Alt Rates\*.xls') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Alt Rates\SEFL MG Alt Rate.xls

In [4]:
df = pd.read_excel(latest_file, sheet_name='Sheet1')
df

,ORIGIN,O. Zip Ranges,DESTINATION,D. Zip Ranges,DISCOUNT %,MINIMUM CHARGE
0,CA-COM Metro,"900-908, 910-916, 918, 926-928",AZ-PHX,"850-853, 857",90.2,115.00
1,CA-COM Metro,"900-908, 910-916, 918, 926-928",CA-COM Metro,"900-908, 910-916, 918, 926-928",93.0,100.00
2,CA-COM Metro,"900-908, 910-916, 918, 926-928",CA-LAX Metro,"917, 923-925",93.0,100.00
3,CA-COM Metro,"900-908, 910-916, 918, 926-928",CO-DEN,800-806,91.9,115.00
4,CA-COM Metro,"900-908, 910-916, 918, 926-928",FL-JAX,320-322,92.5,115.00
5,CA-COM Metro,"900-908, 910-916, 918, 926-928",FL-MIA,330-334,90.9,115.00
6,CA-COM Metro,"900-908, 910-916, 918, 926-928",FL-ORL,"326-329, 335-338, 342, 344, 346-347, 349",89.6,145.00
7,CA-COM Metro,"900-908, 910-916, 918, 926-928",GA-ATL Metro,"300-303, 399",90.8,100.00
8,CA-COM Metro,"900-908, 910-916, 918, 926-928",IL-CHI Metro,601-609,91.5,101.75
9,CA-COM Metro,"900-908, 910-916, 918, 926-928",IL-KEN Metro,600,92.5,109.15
10,CA-COM Metro,"900-908, 910-916, 918, 926-928",IN-IND Metro,460-462,93.0,100.00
11,CA-COM Metro,"900-908, 910-916, 918, 926-928",KS-KCY,660-662,89.2,115.00
12,CA-COM Metro,"900-908, 910-916, 918, 926-928",MA-BOS,010-027,87.7,145.00
13,CA-COM Metro,"900-908, 910-916, 918, 926-928",MD-BLT,"206-212, 214, 216-219",91.9,115.00
14,CA-COM Metro,"900-908, 910-916, 918, 926-928",MI-DET Metro,480-483,93.0,100.00
15,CA-COM Metro,"900-908, 910-916, 918, 926-928",MO-KCY,"640-641, 644, 646-647, 649-650, 653",87.8,145.00
16,CA-COM Metro,"900-908, 910-916, 918, 926-928",MO-STL Metro,"630-631, 633",92.0,115.00
17,CA-COM Metro,"900-908, 910-916, 918, 926-928",NV-REN,894-897,87.6,115.00
18,CA-COM Metro,"900-908, 910-916, 918, 926-928",NY-W.NYM,110-119,90.6,145.00
19,CA-COM Metro,"900-908, 910-916, 918, 926-928",OH-CLV Metro,440-443,93.0,124.85
20,CA-COM Metro,"900-908, 910-916, 918, 926-928",OH-COL,"430-432, 437-438",91.1,100.00
21,CA-COM Metro,"900-908, 910-916, 918, 926-928",PA-LAN,"170-189, 193-196",88.6,115.00
22,CA-COM Metro,"900-908, 910-916, 918, 926-928",PA-PHI Metro,190-192,90.6,145.00
23,CA-COM Metro,"900-908, 910-916, 918, 926-928",TN-NSH Metro,370-372,93.0,100.00
24,CA-COM Metro,"900-908, 910-916, 918, 926-928",TX-DLS Metro,"750-753, 760-761",92.1,100.00
25,CA-COM Metro,"900-908, 910-916, 918, 926-928",TX-HOU Metro,"770, 772-775",91.7,100.00
26,CA-COM Metro,"900-908, 910-916, 918, 926-928",UT-SLC,"840-844, 846",91.6,115.00
27,CA-COM Metro,"900-908, 910-916, 918, 926-928",VA-BLT,"201, 220-223, 226",89.1,145.00
28,CA-COM Metro,"900-908, 910-916, 918, 926-928",WA-SEA Metro,"980-981, 984",91.3,100.00
29,ALL OTHER USA DIRECT POINTS,NaN,ALL OTHER USA DIRECT POINTS,NaN,75.0,155.00
30,ALL OTHER USA DIRECT POINTS,NaN,ALL OTHER CROSS-BORDER DIRECT POINTS,NaN,75.0,250.00
31,ALL OTHER CROSS-BORDER DIRECT POINTS,NaN,ALL OTHER USA DIRECT POINTS,NaN,75.0,250.00

In [14]:
df['MC Discount']=df['MC Discount'].apply(int)

In [17]:
df['Discount'] = df['Discount'].apply(int)

In [20]:
df['Minimum'] = df['Minimum'].apply(int)

In [21]:
df.to_excel('BAaaaaaaaMMMMMMMMMMMMMMMMM.xlsx')

In [4]:
excel_file = pd.ExcelFile(latest_file)
sheet_names = excel_file.sheet_names

print(sheet_names)

['Sheet1', 'Sheet2']

In [7]:
df = pd.read_excel(latest_file, sheet_name='Sheet2')

#df1 = pd.read_excel(latest_file, sheet_name='Product Details')

In [8]:
df['D. Zip Ranges'] = df['D. Zip Ranges'].apply(str)

In [6]:
df.columns

Index(['ORIGIN', 'O. Zip Ranges', 'DESTINATION', 'D. Zip Ranges', 'DISCOUNT %',
       'MINIMUM CHARGE'],
      dtype='object')

In [ ]:
df['cl_1'] = df['cl_1'].apply(str)

In [9]:
weight_list = []

for index, row in df.iterrows():
    # Split the 'To' column by commas
    weights = row['D. Zip Ranges'].split(',')
    for (weight) in (weights):
        new_row = {
            'Dest': weight,
            'DISCOUNT %' : row['DISCOUNT %'],
            'MINIMUM CHARGE' : row['MINIMUM CHARGE'],            
            
            

        }
        
        weight_list.append(new_row)

In [10]:
weight_df = pd.DataFrame(weight_list)

In [11]:
weight_df.head(60)

        Dest  DISCOUNT %  MINIMUM CHARGE
0    850-853        90.2          115.00
1        857        90.2          115.00
2    900-908        93.0          100.00
3    910-916        93.0          100.00
4        918        93.0          100.00
5    926-928        93.0          100.00
6        917        93.0          100.00
7    923-925        93.0          100.00
8    800-806        91.9          115.00
9    320-322        92.5          115.00
10   330-334        90.9          115.00
11   326-329        89.6          145.00
12   335-338        89.6          145.00
13       342        89.6          145.00
14       344        89.6          145.00
15   346-347        89.6          145.00
16       349        89.6          145.00
17   300-303        90.8          100.00
18       399        90.8          100.00
19   601-609        91.5          101.75
20       600        92.5          109.15
21   460-462        93.0          100.00
22   660-662        89.2          115.00
23   010-027        87.7          145.00
24   206-212        91.9          115.00
25       214        91.9          115.00
26   216-219        91.9          115.00
27   480-483        93.0          100.00
28   640-641        87.8          145.00
29       644        87.8          145.00
30   646-647        87.8          145.00
31   649-650        87.8          145.00
32       653        87.8          145.00
33   630-631        92.0          115.00
34       633        92.0          115.00
35   894-897        87.6          115.00
36   110-119        90.6          145.00
37   440-443        93.0          124.85
38   430-432        91.1          100.00
39   437-438        91.1          100.00
40   170-189        88.6          115.00
41   193-196        88.6          115.00
42   190-192        90.6          145.00
43   370-372        93.0          100.00
44   750-753        92.1          100.00
45   760-761        92.1          100.00
46       770        91.7          100.00
47   772-775        91.7          100.00
48   840-844        91.6          115.00
49       846        91.6          115.00
50       201        89.1          145.00
51   220-223        89.1          145.00
52       226        89.1          145.00
53   980-981        91.3          100.00
54       984        91.3          100.00
55       nan        75.0          155.00
56       nan        75.0          250.00
57       nan        75.0          250.00

In [12]:
weight_df.to_excel('dests.xlsx')

In [ ]:
Class_list = []

for index, row in df.iterrows():
    # Split the 'To' column by commas
    classes = row['cl_1'].split(',')
    for (clas) in (classes):
        new_row = {
            'Class': clas,
            'TQL PO':row['TQL PO']
            
            
}
        
        Class_list.append(new_row)

In [ ]:
Dims_list = []

for index, row in df.iterrows():
    # Split the 'To' column by commas
    dims = row['dim_1'].split(',')
    for (dim) in (dims):
        new_row = {
            'TQL PO':row['TQL PO'],
            'Dimensions': dim,
            
        }
        
        Dims_list.append(new_row)

In [ ]:
class_df = pd.DataFrame(Class_list)

In [ ]:
dims_df = pd.DataFrame(Dims_list)

In [ ]:
class_df

In [ ]:
dims_df

Dims_list = []

for index, row in df.iterrows():
    # Split the 'To' column by commas
    Dims = row['Dims'].split(',')
    for (dim) in (Dims):
        new_row = {
            'Zip':row['Zip'],
            'Zip.1':row['Zip.1'],
            'Dims': dim,
            'Total weight' : row['Total weight'], 
            'Total H/U' : row['Total H/U'],
        }
        
        Dims_list.append(new_row)

In [ ]:
weight_df['Class']=class_df['Class']

In [ ]:
weight_df['Dims'] = dims_df['Dimensions']

In [ ]:
weight_df.to_excel('1_2.xlsx')