In [1]:
import pandas as pd
import numpy as np
import os
import glob

In [2]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop')

['.ipynb_checkpoints',
 '658_cs.xlsx',
 'Alt Rates',
 'CANADA.xlsx',
 'CarsonThomasson_6_25xlsx.xlsx',
 'Chrome Passwords.csv',
 'Chunk Folder',
 'CNWYPoints.xlsx',
 'comb_fl',
 'Comb_fl2',
 'Consolidated Valentine Freight Data.xlsx',
 'Copy of CNWYPoints.xlsx',
 'Desktop Discard Pile',
 'desktop.ini',
 'Dialpad.lnk',
 'Edge',
 'Edge output files',
 'Firefox.exe',
 'Fwda increase chart.xlsx',
 'IFstatement.docx',
 'Kutools for Excel.lnk',
 'linehaul',
 'MercuryGAte.jnlp',
 'NTG-FXFE v3.xls',
 'Pandas Custom',
 'Pandas Custom 2',
 'Pandas merging',
 'Pandas_auto',
 'Pricing Wbs',
 'Py combine',
 'Py combine nan files',
 'Python Outputs',
 'Python scripts',
 'Service (3).xlsx',
 'Slack.lnk',
 'SMC',
 'State-to-State-Export-2003-844738.000 (1).csv',
 'State-to-State-Export-2003-844738.000.csv',
 'Temp - Shortcut.lnk',
 'Template files',
 'training docs',
 'wedding intro.docx']

In [3]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\AppData\Local\Temp\*.xls') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\AppData\Local\Temp\Rating_Report_2026_03_06_09_45_43.xls

In [4]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\Downloads\*.xlsx') # * means all if need specific format then *.csv
latest_file_1 = max(list_of_files, key=os.path.getctime)
print(latest_file_1)

C:\Users\matthew.shuff\Downloads\Shipfusion LTL Data_Cooper Brunk.xlsx

In [5]:
df = pd.read_excel(latest_file)

In [6]:
df1= pd.read_excel(latest_file_1)

In [7]:
df1.columns

Index(['Pickup Date', 'BOL', 'Po Number', 'Act. Delivery Date', 'Origin Name',
       'Origin State', 'Origin Zip', 'Destination Name', 'Destination State',
       'Destination Zip', 'Shipment Mode', 'Carrier', 'Total Units',
       'Total Weight', 'Carrier Rate ', 'FXNL', 'ODFL', 'FXNL.1', 'AACT',
       'CNWY', 'EXLA', 'ABFS', 'DAFG', 'OAKH'],
      dtype='object')

In [8]:
car_list = df['Carrier SCAC'].value_counts().index.tolist()

In [9]:
car_list

['FXNL', 'ABFS', 'EXLA']

In [10]:
len(car_list)

3

# Copy slices below into their own variable

In [11]:
#createsliceforeachcarrier
car_1=df[df['Carrier SCAC']==car_list[0]]
car_2=df[df['Carrier SCAC']==car_list[1]]
car_3=df[df['Carrier SCAC']==car_list[2]]
# car_4=df[df['Carrier SCAC']==car_list[3]]
# car_5=df[df['Carrier SCAC']==car_list[4]]
# car_6=df[df['Carrier SCAC']==car_list[5]]
# car_7=df[df['Carrier SCAC']==car_list[6]]
# car_8=df[df['Carrier SCAC']==car_list[7]]

In [17]:
car_1 = car_1[['Primary Reference','Normalized Total']]

In [18]:
car_1

     Primary Reference  Normalized Total
2          60112769706           1972.54
5          60112678751           2262.98
7          60112736264            931.30
9          60112715588           3956.39
12         60112112791            290.84
15         60112735151            253.90
18         60112099471            234.55
21         60111915127            891.99
24         60112569776            229.67
27         60112313355           1694.47
30         60111927914            313.58
33         60112339143            176.67
36         60112320871            332.83
39         60112578180            554.38
42         60112401580            258.07
45         60112056735            727.58
48         60112498752            282.09
51         60112498752            282.09
54         60112498719            372.84
57         60112120601            292.45
59         60112759177            931.30
60         60112365903           4813.28
63         60112055622            508.58
66         60112485005            715.93
69         60112485005            715.93
70         60112050031           2557.53
73         60112320938            229.67
76         60112320915            229.67
79         60112260113            776.63
82         60111971867            813.65
85         60112340598            192.39
88         60111954940           1043.80
91         60112735203            229.67
94         60112462816            229.67
97         60112735223            229.67
100        60112751254           1093.37
102        60112644610           2568.05

In [13]:
df_list = [car_1,car_2,car_3,car_4,car_5,car_6,car_7]

NameError: name 'car_4' is not defined

In [19]:
merge_1 = df1.merge(car_1,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

merge_2 = df1.merge(car_2,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

merge_3 = df1.merge(car_3,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

# merge_4 = df1.merge(car_4,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

# merge_5 = df1.merge(car_5,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

# merge_6 = df1.merge(car_6,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

# merge_7 = df1.merge(car_7,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

# merge_8 = df1.merge(car_8,left_on='BOL',right_on='Primary Reference',how='left',indicator=True)

In [20]:
df1[car_list[0]]=merge_1['Normalized Total']

df1[car_list[1]]=merge_2['Normalized Total']

df1[car_list[2]]=merge_3['Normalized Total']

# df1[car_list[3]]=merge_4['Normalized Total']

# df1[car_list[4]]=merge_5['Normalized Total']

# df1[car_list[5]]=merge_6['Normalized Total']

# df1[car_list[6]]=merge_7['Normalized Total']

# df1[car_list[7]]=merge_8['Normalized Total']

In [22]:
merge_1

,Pickup Date,BOL,Po Number,Act. Delivery Date,Origin Name,Origin State,Origin Zip,Destination Name,Destination State,Destination Zip,...,FXNL.1,AACT,CNWY,EXLA,ABFS,DAFG,OAKH,Primary Reference,Normalized Total,_merge
0,2026-01-05,60112795263,1011490,NaT,FOUR SIGMA FOODS % STACI AMERICAS,CA,92408,UNFI MANCHESTER,PA,17406,...,2813.25,3553.49,2967.07,NaN,NaN,NaN,2299.81,NaN,NaN,left_only
1,2026-01-05,60112793698,1000287,NaT,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI IOWA CITY WAREHOUSE,IA,52240,...,308.36,234.60,323.52,NaN,NaN,243.62,NaN,NaN,NaN,left_only
2,2025-12-31,60112782284,1011486,NaT,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI DAYVILLE WAREHOUSE,CT,6241,...,387.35,440.48,358.85,NaN,NaN,558.14,NaN,NaN,NaN,left_only
3,2025-12-31,60112784113,1009820,NaT,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI - EAST SARASOTA NORTH,FL,34243,...,972.24,482.56,951.94,NaN,NaN,1973.11,NaN,NaN,NaN,left_only
4,2025-12-31,60112785812,3445945,NaT,FOUR SIGMA FOODS % STACI AMERICAS,CA,92408,KEHE DISTRIBUTORS,GA,30135,...,1500.79,1069.96,1604.82,NaN,NaN,NaN,1429.48,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,2025-10-01,60111912193,4509695,2025-10-07,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI GREENWOOD WAREHOUSE,IN,46143,...,926.30,1062.08,372.56,NaN,NaN,1710.26,399.09,NaN,NaN,left_only
365,2025-10-01,60111912279,4507806,2025-10-06,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI RICHBURG,SC,29729,...,562.65,626.54,447.79,309.7,250.42,1449.85,463.62,NaN,NaN,left_only
366,2025-10-01,60111912403,4509683,2025-10-07,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI ATLANTA WAREHOUSE,GA,30336,...,394.53,237.49,806.21,NaN,NaN,116.65,834.99,NaN,NaN,left_only
367,2025-10-06,60111915127,T817,2025-10-06,Staci Americas,CA,92408,Costco Novato - WH #141,CA,94945,...,388.75,249.34,258.76,NaN,NaN,664.18,245.13,6.011192e+10,891.99,both
368,2025-10-03,60111915686,Intelligent Blends - Costco Materials,2025-10-08,Staci CA,CA,92408,Intelligent Blends,CA,92121,...,813.65,424.26,748.06,NaN,NaN,505.92,718.67,NaN,NaN,left_only

In [21]:
df1

,Pickup Date,BOL,Po Number,Act. Delivery Date,Origin Name,Origin State,Origin Zip,Destination Name,Destination State,Destination Zip,...,Carrier Rate,FXNL,ODFL,FXNL.1,AACT,CNWY,EXLA,ABFS,DAFG,OAKH
0,2026-01-05,60112795263,1011490,NaT,FOUR SIGMA FOODS % STACI AMERICAS,CA,92408,UNFI MANCHESTER,PA,17406,...,1995.95,NaN,3233.81,2813.25,3553.49,2967.07,NaN,NaN,NaN,2299.81
1,2026-01-05,60112793698,1000287,NaT,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI IOWA CITY WAREHOUSE,IA,52240,...,285.25,NaN,480.74,308.36,234.60,323.52,NaN,NaN,243.62,NaN
2,2025-12-31,60112782284,1011486,NaT,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI DAYVILLE WAREHOUSE,CT,6241,...,284.10,NaN,404.58,387.35,440.48,358.85,NaN,NaN,558.14,NaN
3,2025-12-31,60112784113,1009820,NaT,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI - EAST SARASOTA NORTH,FL,34243,...,891.82,NaN,1304.83,972.24,482.56,951.94,NaN,NaN,1973.11,NaN
4,2025-12-31,60112785812,3445945,NaT,FOUR SIGMA FOODS % STACI AMERICAS,CA,92408,KEHE DISTRIBUTORS,GA,30135,...,1431.59,NaN,2011.26,1500.79,1069.96,1604.82,NaN,NaN,NaN,1429.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2025-10-01,60111912193,4509695,2025-10-07,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI GREENWOOD WAREHOUSE,IN,46143,...,918.02,NaN,1289.91,926.30,1062.08,372.56,NaN,NaN,1710.26,399.09
361,2025-10-01,60111912279,4507806,2025-10-06,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI RICHBURG,SC,29729,...,398.61,313.58,859.82,562.65,626.54,447.79,309.7,250.42,1449.85,463.62
362,2025-10-01,60111912403,4509683,2025-10-07,FOUR SIGMA FOODS % STACI AMERICAS,IL,60440,UNFI ATLANTA WAREHOUSE,GA,30336,...,505.01,NaN,624.45,394.53,237.49,806.21,NaN,NaN,116.65,834.99
363,2025-10-06,60111915127,T817,2025-10-06,Staci Americas,CA,92408,Costco Novato - WH #141,CA,94945,...,NaN,NaN,796.94,388.75,249.34,258.76,NaN,NaN,664.18,245.13
364,2025-10-03,60111915686,Intelligent Blends - Costco Materials,2025-10-08,Staci CA,CA,92408,Intelligent Blends,CA,92121,...,NaN,NaN,1193.51,813.65,424.26,748.06,NaN,NaN,505.92,718.67

In [ ]:
df1.to_excel('3.6.26.xlsx')