In [1]:
import pandas as pd

import numpy as np

import os

In [2]:

os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas_source_files')

['2024 GRI List of US High Cost Service Areas Final (1).xlsx',
 'Echo-ADM-RRL 30 day_Anastasia Letosky.xlsx',
 'Farmer Brothers 2024 RFP LTL Rate Submission File (2).xlsx',
 'Farmer Brothers results (1).xlsx',
 'FWDA_HCD_src_fl.xlsx',
 'KING SOLOMON ENTERPRISES, INC._Anastasia Letosky.xlsx',
 'MCG Data 11-1-23 thru 1-31-24 with NTG and exceptions (2).xlsx',
 'Moog CTSI LTL Data Nov 2023 thru Jan 2024 NTG results-exceptions.xlsx',
 'Rating_Report_true.xls',
 'S62B - LTL Volume Out 11 and 41_Kelsey Tapia.xlsx',
 'Shipping 04_03_2024_Kekoa Carville.xlsx',
 'True Fitness 2023 Data_Chi An Chen_4vs.xls',
 'zipsfor_myles_transport.xlsx']

In [3]:
df = pd.read_excel('Pandas_source_files\True Fitness 2023 Data_Chi An Chen_4vs.xls')

In [17]:
df1 = pd.read_excel('Pandas_source_files\Rating_Report_true.xls')

In [14]:
df1['Carrier SCAC'] = df1['Carrier SCAC'].str.strip()

In [22]:
df1['Carrier SCAC'].value_counts()

Carrier SCAC
FXNL    1569
RLCA    1555
UPGF    1534
FWDA    1489
Name: count, dtype: int64

In [18]:
df1_fwda = df1[df1['Carrier SCAC']=='FWDA']

In [19]:
df1_fwda

,OID,Primary Reference,Type,Lane ID,Carrier Name,Carrier SCAC,Contract Name,Contract Mode,Contract Service,Service Days,...,Total,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary
0,NaN,13108493,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,3,...,315.55,315.55,2107.45,0.00,0.00,-1881.95,80.05,10.0,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
4,NaN,13122315,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,3,...,367.87,367.87,2199.10,0.00,63.35,-1990.96,96.38,0.0,0,NaN
8,NaN,13108492,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,4,...,816.17,816.17,5019.46,0.00,0.00,-4417.12,213.83,0.0,0,NaN
12,NaN,13122316,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,3,...,536.12,536.12,3297.15,0.00,0.00,-2901.49,140.46,0.0,0,NaN
16,NaN,13108491,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,2,...,355.93,355.93,2653.37,0.00,0.00,-2390.69,93.25,0.0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6124,NaN,13050515,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,3,...,578.88,578.88,3923.77,0.00,0.00,-3503.93,149.04,10.0,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
6128,NaN,13050518,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,2,...,166.10,166.10,1190.11,0.00,0.00,-1067.53,43.52,0.0,0,NaN
6132,NaN,13106137,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,2,...,281.34,281.34,1730.24,0.00,0.00,-1522.61,73.71,0.0,0,NaN
6139,NaN,13106138,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,2,...,169.38,169.38,1047.34,34.93,0.00,-957.27,44.38,0.0,0,NaN
6143,NaN,13050519,Carrier,NaN,FORWARD AIR INC,FWDA,FP FWDA MG LTL,LTL,Standard,2,...,421.50,421.50,3110.68,0.00,0.00,-2799.61,110.43,0.0,0,NaN

In [20]:
df1_fxnl = df1[df1['Carrier SCAC']=='FXNL']df

In [23]:
df1_rlca = df1[df1['Carrier SCAC']=='RLCA']

In [25]:
df1_upgf = df1[df1['Carrier SCAC']=='UPGF']

In [26]:
df1_fxnl = df

,OID,Primary Reference,Type,Lane ID,Carrier Name,Carrier SCAC,Contract Name,Contract Mode,Contract Service,Service Days,...,Total,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary
3,NaN,13108493,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,4,...,436.02,436.02,2262.58,0.00,0.00,-1934.51,85.950000,22.0,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
7,NaN,13122315,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,3,...,374.84,374.84,2170.72,0.00,62.53,-1936.23,77.820000,0.0,0,NaN
11,NaN,13108492,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,4,...,720.78,720.78,5054.30,0.00,0.00,-4483.16,149.640000,0.0,0,NaN
15,NaN,13122316,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,3,...,551.73,551.73,3287.12,0.00,0.00,-2849.93,114.540000,0.0,0,NaN
19,NaN,13108491,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,2,...,510.90,510.90,3582.54,0.00,0.00,-3177.71,106.070000,0.0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6131,NaN,13050518,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,2,...,239.15,239.15,945.83,34.38,0.00,-790.71,49.650000,0.0,0,NaN
6135,NaN,13106137,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,2,...,280.87,280.87,1673.37,0.00,0.00,-1450.81,58.310000,0.0,0,NaN
6138,NaN,13050517,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,5,...,433.57,433.57,2357.46,0.00,435.74,-2449.64,90.010000,0.0,0,NaN
6142,NaN,13106138,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,2,...,208.23,208.23,431.84,112.32,0.00,-379.16,43.230001,0.0,0,NaN
6146,NaN,13050519,Carrier,NaN,TFORCE FREIGHT,UPGF,FP UPGF LTL MG,LTL,Standard,2,...,419.99,419.99,2483.56,0.00,0.00,-2150.76,87.190000,0.0,0,NaN

In [27]:
df1_fwda.to_csv('df_fwda.csv')

In [28]:
df1_rlca.to_csv('df1_rlca.csv')

In [29]:
df1_upgf.to_csv('upgf.csv')

In [30]:
df1_fxnl.to_csv('fxnl.csv')

In [ ]:
df.rename(columns=df.iloc[0], inplace = True)

In [ ]:
df = df.iloc[1:]

In [ ]:
df