In [1]:
import pandas as pd

import numpy as np

import os

In [2]:

os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas_source_files')

['2024 GRI List of US High Cost Service Areas Final (1).xlsx',
 'Echo-ADM-RRL 30 day_Anastasia Letosky.xlsx',
 'Farmer Brothers 2024 RFP LTL Rate Submission File (2).xlsx',
 'Farmer Brothers results (1).xlsx',
 'FWDA_HCD_src_fl.xlsx',
 'KING SOLOMON ENTERPRISES, INC._Anastasia Letosky.xlsx',
 'MCG Data 11-1-23 thru 1-31-24 with NTG and exceptions (2).xlsx',
 'Moog CTSI LTL Data Nov 2023 thru Jan 2024 NTG results-exceptions.xlsx',
 'S62B - LTL Volume Out 11 and 41_Kelsey Tapia.xlsx']

In [3]:
df = pd.read_excel(r'Pandas_source_files\FWDA_HCD_src_fl.xlsx')

In [4]:
df1 = pd.read_excel(r'Pandas_source_files\FWDA_HCD_src_fl.xlsx',sheet_name='B')

In [5]:
df2 = pd.read_excel(r'Pandas_source_files\FWDA_HCD_src_fl.xlsx',sheet_name='C')

In [6]:
df3 = pd.read_excel(r'Pandas_source_files\FWDA_HCD_src_fl.xlsx',sheet_name='D')

In [7]:
df = df.dropna(axis=1, how='all')

In [8]:
df1 = df1.dropna(axis=1, how='all')

In [9]:
len(df)

225

In [10]:
df

,Note A,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,Charge,NaN,30,NaN,NaN,NaN,NaN
1,87035.0,87532.0,87533.0,87544,87545.0,76093,1230.0,1236.0,1238.0,1240.0
2,1254.0,1257.0,1258.0,01262,1266.0,12017,12028.0,12029.0,12031.0,12035.0
3,12037.0,12042.0,12043.0,12050,12051.0,12057,12058.0,12060.0,12071.0,12075.0
4,12083.0,12092.0,12106.0,12120,12122.0,12130,12132.0,12136.0,12156.0,12157.0
...,...,...,...,...,...,...,...,...,...,...
220,45877.0,45881.0,48140.0,48177,49235.0,49248,49276.0,33571.0,33575.0,33576.0
221,33586.0,33598.0,33801.0,33802,33803.0,33804,33805.0,33806.0,33807.0,33809.0
222,33810.0,33811.0,33812.0,33813,33815.0,34220,34669.0,24311.0,37640.0,37657.0
223,72956.0,72957.0,74001.0,74002,74010.0,74020,74022.0,74027.0,74029.0,74031.0
224,74035.0,74039.0,74042.0,74043,74044.0,74051,74054.0,NaN,NaN,NaN

In [11]:
df2 = df2.dropna(axis=1, how='all')

In [12]:
df3 = df3.dropna(axis=1, how='all')

In [13]:
df = df.iloc[1:]

In [14]:
df1 = df1.iloc[1:]

In [15]:
df2 = df2.iloc[1:]

In [16]:
df3 = df3.iloc[1:]

In [17]:
df = df.stack()

In [18]:
df1 = df1.stack()

In [19]:
df2 = df2.stack()

In [20]:
df3 = df3.stack()

In [21]:
s = df

s.name = 'value'

s.reset_index()

s=pd.DataFrame(s)

In [22]:
b = df1

b.name = 'value'

b.reset_index()

b=pd.DataFrame(b)

In [23]:
c = df2

c.name = 'value'

c.reset_index()

c=pd.DataFrame(c)

In [24]:
d = df2

d.name = 'value'

d.reset_index()

d=pd.DataFrame(d)

In [25]:
s

                  value
1   Note A      87035.0
    Unnamed: 1  87532.0
    Unnamed: 2  87533.0
    Unnamed: 3    87544
    Unnamed: 4  87545.0
...                 ...
224 Unnamed: 2  74042.0
    Unnamed: 3    74043
    Unnamed: 4  74044.0
    Unnamed: 5    74051
    Unnamed: 6  74054.0

[2237 rows x 1 columns]

In [26]:
s['Amnt'] = 30

In [27]:
b['Amnt'] = 60

In [28]:
c['Amnt'] = 90

In [29]:
d['Amnt'] = 90

In [30]:
fn = pd.concat([s,b,c,d])

In [31]:
fn.to_csv('stack_zips.csv')