In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas_source_files')

['2024 GRI List of US High Cost Service Areas Final (1).xlsx',
 'Echo-ADM-RRL 30 day_Anastasia Letosky.xlsx',
 'Farmer Brothers 2024 RFP LTL Rate Submission File (2).xlsx',
 'Farmer Brothers results (1).xlsx',
 'Freightview_shipments_5c672cb8a75f15000491c0d_Ahmos III Zu-Bolton.xlsx',
 'FWDA_HCD_src_fl.xlsx',
 'KING SOLOMON ENTERPRISES, INC._Anastasia Letosky.xlsx',
 'MCG Data 11-1-23 thru 1-31-24 with NTG and exceptions (2).xlsx',
 'Moog CTSI LTL Data Nov 2023 thru Jan 2024 NTG results-exceptions.xlsx',
 'Rating_Report_true.xls',
 'S62B - LTL Volume Out 11 and 41_Kelsey Tapia.xlsx',
 'Shipping 04_03_2024_Kekoa Carville.xlsx',
 'Shipping 04_16_2024_Khalil Walker.xlsx',
 'True Fitness 2023 Data_Chi An Chen_4vs.xls',
 'zipsfor_myles_transport.xlsx']

In [3]:
df = pd.read_excel('Pandas_source_files\Freightview_shipments_5c672cb8a75f15000491c0d_Ahmos III Zu-Bolton.xlsx')

df1 = pd.read_excel('Pandas_source_files\Freightview_shipments_5c672cb8a75f15000491c0d_Ahmos III Zu-Bolton.xlsx',sheet_name='Charges')

In [4]:
df3 = pd.read_excel('Pandas Merging\zhu_bolton_od.xlsx')

In [5]:
df.columns

Index(['FV Link', 'Shipment ID', 'BOL number', 'Booked By', 'Status', 'Mode',
       'Bill recipient / 3rd party', 'Tracking number',
       'Pickup confirmation number', 'Booked datetime',
       ...
       'Load reference numbers', 'Mark Up %', 'Total w/ Markup', 'Distance',
       'Distance unit of measure', 'Quoted by', 'Invoice date',
       'NTG Rate Margin Added', 'No Margin', 'SCAC'],
      dtype='object', length=101)

In [7]:
df = df[df['Length 1']>95]

In [8]:
df1.Name.value_counts()

Name
linehaul                    679
fuel                        637
discount                    513
arrival schedule            196
over dimension               68
compliance surcharge         35
liftgate delivery            34
guaranteed                   30
deficit charge               28
limited access delivery      26
residential delivery         23
arrival notice               23
minimum charge               17
farm delivery                10
high cost area surcharge      7
other                         6
stadium delivery              1
tradeshow delivery            1
Name: count, dtype: int64

In [9]:
od_lis = df1[df1['Name']=='over dimension']

In [10]:
od_lis

                   Shipment ID            Name  Amount Currency
6     658dd855df50a66a37778222  over dimension     0.0      usd
40    659567d421ef65040668dee0  over dimension     0.0      usd
48    65957a44ba2d6824a314472a  over dimension     0.0      usd
138   65984ef06bf8638759d5fe53  over dimension   250.0      usd
164   659c348a71c85508880bd16a  over dimension     0.0      usd
...                        ...             ...     ...      ...
2292  66047f80ce11b73fc27d02ec  over dimension     0.0      usd
2293  66047f80ce11b73fc27d02ec  over dimension     0.0      usd
2299  66056cfa36546c7462a82364  over dimension    50.0      usd
2315  6605c9514b3817e86ce3dc8c  over dimension    45.0      usd
2333  6607023b171a788cbdd6825f  over dimension     0.0      usd

[68 rows x 4 columns]

In [11]:
od_lis = od_lis['Shipment ID'].tolist()

In [12]:
od_lis

['658dd855df50a66a37778222',
 '659567d421ef65040668dee0',
 '65957a44ba2d6824a314472a',
 '65984ef06bf8638759d5fe53',
 '659c348a71c85508880bd16a',
 '659c35aa75b5976975faf796',
 '65a15a874d68bfccbf3da63e',
 '65a15ba4f81f52266333d75a',
 '65a15c57c38237055357ecfd',
 '65a59f7a7b58957d6f05d3fa',
 '65a830f74e4239c3582e22df',
 '65a8521b0343e5f6f23cd85b',
 '65a85115e2fbb8b206b1ae49',
 '65abe28c82cb33e78a6c08c9',
 '65abe2f79db0f65e5736db49',
 '65b51260c5b777361a91c8de',
 '65b51e29c5b777361a91cca5',
 '65b81772a22bb793d0c1e8bb',
 '65b81772a22bb793d0c1e8bb',
 '65ba8ec33433640d75121b53',
 '65ba900cbef00d61caff52aa',
 '65ba900cbef00d61caff52aa',
 '65ba914cfb235028f2560285',
 '65ba914cfb235028f2560285',
 '65ba97b6c39fd4b26e9da411',
 '65ba9ffcb431276a5a13a59f',
 '65baa62a6d5041f2689aadac',
 '65babd1ab431276a5a13cdd0',
 '65bd2ca861946c30fca3ed68',
 '65bd52e895372f25ff1db7c6',
 '65ccc810fa828c50d5b914ca',
 '65ccf65d01eb80d7b89f5337',
 '65ccf65d01eb80d7b89f5337',
 '65ccf95f8680ec1359c4a29f',
 '65ccf9f4340eda1601b8846f',
 '65ce220f78452bcf42d2eaee',
 '65cf68247b984ee7dff77a79',
 '65db8c4e5ead8ef8fa5a85ce',
 '65db8dc9d1d481f257c2faee',
 '65db8dc9d1d481f257c2faee',
 '65db8f3b1f9196a091e75153',
 '65de0596c1cc2868db9e8aca',
 '65de25935889f5abfde14a19',
 '65df663c5f09403a5459d06a',
 '65e08d11009783cc34b7dc97',
 '65e889408e3d12f8aa8dd2db',
 '65ef1376f141041070e42862',
 '65f0457fceface7ae0dd4235',
 '65f0c85f71f20b4a027a2711',
 '65f36822b60c4e1ed3f3aec7',
 '65f35ed195622891ffa57c07',
 '65f457011d43a4b01d96ee64',
 '65f466a607f90b06224b36a9',
 '65f9cabd0fe1bf8218b7bfb3',
 '65f9e7670fe1bf8218b7eaeb',
 '65facfbfb9fcf9619a750792',
 '65faf682ba490183c9afbb2d',
 '65fb19e8b9fcf9619a757b78',
 '6601c5a778ff9ed22cb545eb',
 '660314bdef748b4a14cba6cd',
 '660315d217b4a5f6c3349dbd',
 '6603165017b4a5f6c3349e56',
 '660316e5bf1b1d2977e7cae6',
 '66047f80ce11b73fc27d02ec',
 '66047f80ce11b73fc27d02ec',
 '66056cfa36546c7462a82364',
 '6605c9514b3817e86ce3dc8c',
 '6607023b171a788cbdd6825f']

In [15]:
df_od = df[~df['Shipment ID'].isin(od_lis)]

In [16]:
df_od

,FV Link,Shipment ID,BOL number,Booked By,Status,Mode,Bill recipient / 3rd party,Tracking number,Pickup confirmation number,Booked datetime,...,Load reference numbers,Mark Up %,Total w/ Markup,Distance,Distance unit of measure,Quoted by,Invoice date,NTG Rate Margin Added,No Margin,SCAC
193,65b6ab1dc2b27ee31d175fab,65b6ab1dc2b27ee31d175fab,10661522,Tyler Gehlhausen,delivered,truckload,False,NaN,10661522,01/29/2024 02:42 PM,...,NaN,0,6150.0,NaN,NaN,Tyler Gehlhausen,NaN,NaN,NaN,NaN
498,65e8756d943362695ea5e007,65e8756d943362695ea5e007,10907689,Tyler Bartley,scheduled,truckload,False,NaN,7427915,03/06/2024 05:06 PM,...,NaN,0,825.0,NaN,NaN,Tyler Bartley,NaN,NaN,NaN,NaN
563,65f1be52967ee6e8e74b0c98,65f1be52967ee6e8e74b0c98,10953520,Tyler Bartley,scheduled,truckload,False,NaN,7444243,03/13/2024 03:34 PM,...,NaN,0,1000.0,NaN,NaN,Tyler Bartley,NaN,NaN,NaN,NaN
624,65fdd55811f2f1cb3e6b9c67,65fdd55811f2f1cb3e6b9c67,11021997,Tyler Bartley,scheduled,truckload,False,NaN,7470335,03/22/2024 07:29 PM,...,NaN,0,750.0,NaN,NaN,Tyler Bartley,NaN,NaN,NaN,NaN

In [ ]:
df_od.to_csv('overdims.csv')

In [ ]:
df_od[['Shipment ID','services']]

In [ ]:
df3['Costs'] = x-y

In [ ]:
df3.Costs

In [ ]:
df3.to_csv('Zhu_costs.csv')

In [ ]:
df1

In [ ]:
df1 = df1[['Normalized Total', 'Carrier SCAC', 'Primary Reference']]

In [ ]:
df1['Carrier SCAC'].value_counts()

In [ ]:
merged = df.merge(df1,how='left', left_on='PR', right_on='Primary Reference',indicator=True)

In [ ]:
merged['_merge'].value_counts()

In [ ]:
merged[merged['_merge']=='left_only']

In [ ]:
merged['Carrier SCAC_y']= merged['Carrier SCAC_y'].fillna('FCSY')

In [ ]:
merged

In [ ]:
a = merged[merged['Carrier SCAC_y']=='EXLA']

In [ ]:
a

In [ ]:
b = merged[merged['Carrier SCAC_y']=='FCSY']

In [ ]:
b

In [ ]:
c = merged[merged['Carrier SCAC_y']=='RDFS']

In [ ]:
d = merged[merged['Carrier SCAC_y']=='CTII']

In [ ]:
a.to_excel('exla.xlsx')

In [ ]:
b.to_excel('fcsy.xlsx')

In [ ]:
c.to_excel('RDFS.xlsx')

In [ ]:
d.to_excel('CTII.xlsx')